name: Build Zed

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Rust toolchain
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # Configure long path support
      - name: Enable Git long paths
        run: git config --system core.longpaths true

      - name: Enable Windows long paths
        run: |
          New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" `
                          -Name "LongPathsEnabled" `
                          -Value 1 `
                          -PropertyType DWORD `
                          -Force
        shell: powershell

      # Install CMake via Chocolatey if not present
      - name: Install CMake
        run: choco install cmake --installargs '"ADD_CMAKE_TO_PATH=System"' -y
        shell: cmd
        if: !contains(env.PATH, 'CMake')

      # Build Zed
      - name: Build Release
        run: cargo build --release

      # Run tests
      - name: Run Tests
        run: cargo test --workspace

      # Upload artifact
      - name: Upload Zed executable
        uses: actions/upload-artifact@v4
        with:
          name: zed-windows
          path: target/release/zed.exe
          if-no-files-found: error
