name: Zed Build

on:
  workflow_dispatch:
    inputs:
      build_mode:
        description: "Build mode: release or debug"
        required: false
        default: "release"
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build Zed
        id: build
        working-directory: ./zed   # Change this if Cargo.toml is in another folder.
        shell: cmd
        run: |
          if "%BUILD_MODE%"=="release" (
            cargo build --release
          ) else (
            cargo build
          )
        env:
          BUILD_MODE: ${{ github.event.inputs.build_mode }}

      - name: Run Tests
        working-directory: ./zed   # Ensure this points to the directory containing Cargo.toml.
        run: cargo test --workspace

      - name: Archive Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zed-${{ env.BUILD_MODE }}
          path: zed/target/${{ env.BUILD_MODE }}/zed.exe   # Adjust if your executable name or path differs.
          if-no-files-found: error
