name: Build Zed

on:
  workflow_dispatch:
    inputs:
      build_mode:
        description: "Build mode: release or debug"
        required: false
        default: "release"
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust Toolchain
        # Use dtolnay's action as a maintained alternative to actions-rs/toolchain.
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          override: true

      - name: Build Zed
        id: build
        shell: cmd
        run: |
          if "%BUILD_MODE%"=="release" (
            cargo build --release
          ) else (
            cargo build
          )
        env:
          BUILD_MODE: ${{ github.event.inputs.build_mode }}

      - name: Run Tests
        run: cargo test --workspace

      - name: Archive Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zed-${{ env.BUILD_MODE }}
          # Assumes the executable is built as "zed.exe" in target/release or target/debug
          path: target/${{ env.BUILD_MODE }}/zed.exe
          if-no-files-found: error
